name: Project Restore
description: 'Restore .NET packages and tools'
runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Fetch packages cache
      uses: actions/cache@v3
      id: nuget-cache
      with:
        path: |
          ~/.nuget/packages
          ~/.dotnet/toolResolverCache
          **/obj
          !.git/**/obj
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/dotnet-tools.json', '**/*.csproj') }}

    - name: Restore dotnet tools
      shell: bash
      run: dotnet tool restore

    - name: Restore packages
      shell: bash
      run: |
          dotnet restore
